baseURL: "https://jdhagood.github.io/"
languageCode: en-us
build:
  writeStats: true
params:
  title: Project Portfolio
  author: JD Hagood
  description: JD Hagood's Personal Project Portfolio
  copyright: >-
    powered by [hugo](https://gohugo.io/) & deployed on
    [GitHub Pages](https://pages.github.com/)
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
              <link rel="manifest" href="site.webmanifest">
              <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
              <link rel="shortcut icon" href="favicon.ico">




  profile:
    name: "JD Hagood"
    tagline: Project Portfolio
    photo: jd.jpg
  social:
    title: Links
    list:
      - icon: fab fa-linkedin-in
        url: "https://www.linkedin.com/in/jd-hagood-3053a0218/"
        title: LinkedIn
      - icon: fab fa-github
        url: "https://github.com/jdhagood/keygenV2"
        title: GitHub
  showInAccordion:
    - item: aboutme
      expand: true
    - item: experience
    - item: education
    - item: publication
    - item: project
    - item: skill
    - item: hobby
  aboutme:
    title: About Me
    icon: fas fa-user
    description: My name is JD Hagood, and I am currently a Sophomore at the Massachusetts Institute of
                 Technology studying electrical engineering with computer science. I like to spend
                 my time in the maker spaces on campus turning my project ideas into reality. You can keep
                 up with some of my recent projects on this website!




  education:
    title: Education
    icon: fas fa-graduation-cap
    list:
      - degree: Electrical Engineering with Computer Science
        college: Massachusetts Institute of Technology
        dates: 2023 - Present
      - degree: Highschool Diploma
        college: The Mississippi School for Math and Science
        dates: 2021 - 2023
  project:
    title: Projects
    icon: fas fa-project-diagram
    list:
      - title: Automated Etch-a-Sketch
        url: "/projects/etch_a_sketch/"
        description: Using AI to level up my etch-a-sketch drawing skills; Making a compact text to etch-a-sketch drawing robot.




      - title: Single Board Games
        url: "/projects/single_board_games/"
        description: Milling out PCBs to have fun with for hours; Making handheld PCB games with the ATtiny3226.




      - title: 3D Printed Clothes
        url: "/projects/3d_printed_clothes/"
        description: Pushing my 3D printing skills to the limit to have the coolest clothes at a party; Leveraging the under-extrusion of filament to create textiles.




      - title: "Educational 3D Printed Speaker Kits"
        url: "/projects/speaker_kits/"
        description: Utilizing the rapid manufacturing of 3D printers to create over 200 educational kits for students to build their own speakers for the MIT Spokes program.




      - title: Recept Poetry Robot
        url: "/projects/poetry_robot/"
        description: Using a thermal printer to print out poems on demand; Web Scraping poetryFoundation.org and putting poems on a receipt.




      - title: NFC Pen Testing Glove
        url: "/projects/nfc_glove/"
        description: Using an arduino and MIFARE reader to display the security concerns of RFID tap systems on most college campuses.




  skill:
    title: Skills
    panelId: skill-panel
    icon: fas fa-cogs
    list:
      - skill: Embedded Systems
        skillrating: 90
      - skill: PCB Design
        skillrating: 80
      - skill: Python Programming
        skillrating: 90
      - skill: C/C++ Programming
        skillrating: 70
      - skill: Onshape CAD
        skillrating: 80
      - skill: Digital Manufacturing Tools
        skillrating: 80
      - skill: Soldering
        skillrating: 95
  hobby:
    title: Hobbies/Clubs
    icon: fas fa-bicycle
    list:
      - hobby: Cycling
      - hobby: Hiking with the MIT Outdoors Club
      - hobby: Making
      - hobby: MIT Solar Electric Vehicle Team
 
  customCSS: "css/custom.css"